---

#############################
#############################
## JavaScript Linter rules ##
#############################
#############################

############
# Env Vars #
############
env:
  browser: true
  es6: true
  es2017: true
  jest: true

###############
# Global Vars #
###############
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

extends: "eslint:recommended"

###############
# Parser vars #
###############
parserOptions:
  ecmaVersion: 8
  sourceType: module

ignorePatterns: ["**/cypress/**/*.js"]

#########
# Rules #
#########
rules:
  no-case-declarations: "warn"
  cypress/no-unnecessary-waiting: "off"
  no-unused-vars: "warn"
  no-fallthrough: "warn"
  no-var: "error"
  indent: "warn"
  max-len: ["warn", { "code": 100, "tabWidth": 4 }]
  id-length: ["warn", { "min": 3 }]
  camelcase: ["warn", { allow: ["^._"]}] # ignore variables that start with a single letter and an underscore, i.e o_btn