name: Build and Deploy
on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Build
        run: |
          # make file executable
          chmod +x "${GITHUB_WORKSPACE}/scripts/build.sh"

          sh "${GITHUB_WORKSPACE}/scripts/build.sh"

      - name: Archive Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build