# This is a basic workflow to help you get started with Actions

name: Generate Documentation

# Controls when the action will run.
on:
  pull_request:
    paths:
      - "source/**"
    branches:
      - main
    types:
      - closed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  gen_docs:
    if: github.event.pull_request_merged == true
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Check out the repository

      - name: Checkout Code
        uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: install JSDoc
        # npm install will respect the package.json, while npm ci will respect package-lock.json
        run: npm install
      # Generate the JSDocs under source directory and output to docs directory
      - name: Generate Documentation
        run: npm run docs
